build: add missing main.ui
Summary: kwinscreenedgeconfigform.cpp:23:10: fatal error: ui_main.h: No such file or
directory

Test Plan: kwin builds again.

Reviewers: #kwin, davidedmundson

Reviewed By: #kwin, davidedmundson

Subscribers: kwin

Tags: #kwin

Differential Revision: https://phabricator.kde.org/D29212