fix: add missing include for libc++ after c2f41815196a
main.cpp:298:77: error: use of undeclared identifier 'errno'
        qCWarning(KWIN_CORE, "Failed to query monotonic time: %s", strerror(errno));